In [7]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import svm
import seaborn as sns
from catboost import CatBoostClassifier, Pool, cv
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score,confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler

In [5]:
data = pd.read_csv("D:/projtest2023/mq5/XAUUSD_D1.csv")
data = data.drop(['Unnamed: 0', 'index', 'time', 'Profit','real_volume_change'], axis=1, inplace=False)
data = data.dropna(axis=0)

In [10]:
#特征和标签
X = data.drop(columns = ['Type'])
Y = data['Type']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state = 3)

In [13]:
# 创建SVM模型对象
model = svm.SVC(kernel='linear')
# # 获取超平面的系数w和截距b
# w = clf.coef_[0]
# b = clf.intercept_[0]

# # 计算超平面上两个点的坐标
# x = np.linspace(0, 10, 100)
# y = (-w[0] * x - b) / w[1]

In [14]:
# 训练模型
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [15]:
# 在验证集上进行预测
y_pred = model.predict(X_test)
#混淆矩阵
cmatrix = confusion_matrix(Y_test, y_pred)
cmatrix[::-1, ::-1]

array([[ 26, 201],
       [ 36, 538]], dtype=int64)

In [16]:
#test
accuracy = accuracy_score(Y_test, y_pred)
f1 = f1_score(Y_test, y_pred)
recall = recall_score(Y_test, y_pred)
precision = precision_score(Y_test, y_pred)
print("Accuracy:", accuracy,"f1:", f1,"recall:", recall,"precision:", precision)

Accuracy: 0.704119850187266 f1: 0.17993079584775085 recall: 0.1145374449339207 precision: 0.41935483870967744


# StandardScaler

In [17]:
#标准化StandardScaler()
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [18]:
# 训练模型
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [20]:
# 在验证集上进行预测
y_pred = model.predict(X_test)
#混淆矩阵
cmatrix = confusion_matrix(Y_test, y_pred)
cmatrix

D:\python\envs\python39\lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


array([[574,   0],
       [227,   0]], dtype=int64)

# class_weight="balanced"

In [23]:
model = svm.SVC(kernel='linear')
# 训练模型
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [24]:
# 在验证集上进行预测
y_pred = model.predict(X_test)
#混淆矩阵
cmatrix = confusion_matrix(Y_test, y_pred)
cmatrix

D:\python\envs\python39\lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


array([[574,   0],
       [227,   0]], dtype=int64)